[project]
name = "drone-stabilization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "notebook>=7.3.3",
    "numpy<2.0",
    "scipy>=1.15.2",
    "tqdm>=4.67.1",
]
